print('what do you get when you cross a snowman with vampire?')
input()
print('Frostbite')
input()
print('What do dentists call an astronaut\'s cavity?')
input()
print('A black hole!')
input()
print('Knock Knock')
input()
print("Who's there?")
input()
print('Interuppting Cow.')
input()
print('Interuppting cow wh', end=' ')
print('-Moo!')
